title = "Aliaksei Zhynhiarouski"
theme = "Detox"
baseurl = "https://aliaksei-lithium.github.io/"
languageCode = "en-us"
author = "Aliaksei Zhynhiarouski"

[social]
  github = "aliaksei-lithium"
  twitter_name = "a_lithium"