title = "Aliaksei Zhynhiarouski"
theme = "Detox"
baseurl = "https://aliaksei-lithium.github.io/"
languageCode = "en-us"
author = "Aliaksei Zhynhiarouski"

[params]
  author = "Aliaksei Zhynhiarouski"
  description = "Personal site and blog"
  googleAnalytics = "UA-92309001-1"
  disqus = "aliaksei-lithium"

[social]
  github = "aliaksei-lithium"
  twitter_name = "a_lithium"